"""execlist.py — the execution list, rendered into the markdown from the tree.

A milestone states the order its features are built in; a feature states the
order its stories are built in. Both are what a reader actually wants from the
file, and both are exactly the thing standing doctrine forbids hand-maintaining:
"do not hand-maintain a story list in a feature file — that is a second
scoreboard and it will lie."

It lies because a HUMAN maintains it. Generated between markers, from the same
tree `pm status` reads, it is not a second source of truth — it is a rendered
view of the only one. V6 fails when the rendered block and the tree disagree, so
a stale list is a gate failure rather than a quiet inaccuracy.

Order is: phase (numeric, then `seam`, then unphased), then dependency order
within a bucket, then name. Dependency order is Kahn with a name tiebreak, so
the output is deterministic — a list that reshuffled between runs would churn
the diff and train people to ignore it.
"""
from __future__ import annotations

from pathlib import Path

from godot_devkit.core import apply
from godot_devkit.repo.pm import model, validate

OPEN = '<!-- pm:execution -->'
CLOSE = '<!-- /pm:execution -->'
NOTE = ('*Generated by `godot-devkit pm sync` from the tree — do not edit. '
        '`pm status` is the live read; this is the ORDER.*')


class Refusal(Exception):
    """A grain file this renderer cannot rewrite CORRECTLY. Nothing is written.

    Two members: a file that is not UTF-8 (there is no honest way to even ask
    whether it carries a block), and a marker pair that is broken — one marker
    missing, or CLOSE before OPEN. The old behaviour for broken markers was the
    append branch, which grew the file by one fresh block per `pm sync` run,
    forever, at exit 0 — a diff that looks legitimate and is not (rule 4's
    write-side sin). The message names every offending file and its markers.
    """


def _phase_key(phase: str) -> tuple:
    if phase.isdigit():
        return (0, int(phase), '')
    if phase == 'seam':
        return (1, 0, '')
    return (2, 0, '')


def _toposort(names: list[str], deps: dict[str, list[str]]) -> list[str]:
    """Kahn, name-tiebroken. A cycle degrades to name order (V5 reports it)."""
    remaining = set(names)
    out: list[str] = []
    while remaining:
        ready = sorted(n for n in remaining
                       if not (set(deps.get(n, ())) & remaining))
        if not ready:                       # cycle — V5 owns that finding
            out.extend(sorted(remaining))
            break
        out.extend(ready)
        remaining -= set(ready)
    return out


def _short(gid: str) -> str:
    return gid.rpartition('/')[2] or gid


def milestone_rows(cfg: model.PmConfig, mdir: Path) -> list[str]:
    views = [model.read_feature(f) for f in model.feature_files(mdir)]
    by_id = {v.fid: v for v in views}
    deps: dict[str, list[str]] = {}
    for v in views:
        try:
            refs = validate._refs(v.path, 'depends_on')
        except validate.Unparseable:
            refs = []
        deps[v.fid] = [r for r in refs if r in by_id]
    buckets: dict[tuple, list[str]] = {}
    for v in views:
        buckets.setdefault(_phase_key(v.phase), []).append(v.fid)
    rows, n = [], 0
    for key in sorted(buckets):
        ordered = _toposort(sorted(buckets[key]), deps)
        label = ('phase ' + str(key[1]) if key[0] == 0
                 else 'seam' if key[0] == 1 else 'unphased')
        if len(buckets) > 1 or key[0] != 2:
            rows.append(f'\n**{label}**\n')
        for fid in ordered:
            v = by_id[fid]
            n += 1
            blockers = [_short(d) for d in deps[fid]]
            after = f' — after {", ".join(blockers)}' if blockers else ''
            rows.append(f'{n}. `{_short(fid)}` · {v.status} · '
                        f'{v.done_n}/{v.total} stories{after}')
    return rows


def feature_rows(cfg: model.PmConfig, ffile: Path) -> list[str]:
    stories = model.story_files(ffile)
    ids = {model.field_of(s, 'id'): s for s in stories}
    deps: dict[str, list[str]] = {}
    for sid, sfile in ids.items():
        try:
            refs = validate._refs(sfile, 'depends_on')
        except validate.Unparseable:
            refs = []
        deps[sid] = [r for r in refs if r in ids]
    rows = []
    for n, sid in enumerate(_toposort(sorted(ids), deps), 1):
        status = model.field_of(ids[sid], 'status')
        owner = model.field_of(ids[sid], 'owner')
        blockers = [_short(d) for d in deps[sid]]
        after = f' — after {", ".join(blockers)}' if blockers else ''
        who = f' ({owner})' if owner else ''
        rows.append(f'{n}. `{_short(sid)}` · {status}{who}{after}')
    return rows


def block_for(cfg: model.PmConfig, path: Path) -> str:
    rows = (milestone_rows(cfg, path.parent) if path.name == model.MILESTONE_DOC
            else feature_rows(cfg, path))
    body = '\n'.join(rows) if rows else '_(nothing yet)_'
    return f'{OPEN}\n{NOTE}\n\n{body}\n{CLOSE}'


def _replace(text: str, block: str, rel: str) -> str:
    start, end = text.find(OPEN), text.find(CLOSE)
    if start == -1 and end == -1:
        sep = '' if text.endswith('\n\n') else ('\n' if text.endswith('\n') else '\n\n')
        return f'{text}{sep}## Execution order\n\n{block}\n'
    # Half a marker pair, or a reversed one, is NOT "no block" — treating it as
    # the append case grew the file by a fresh block every run, at exit 0.
    if start == -1:
        raise Refusal(f'{rel}: {CLOSE!r} appears without {OPEN!r} — restore '
                      f'the opening marker (or delete the closing one); '
                      f'nothing was written')
    if end == -1:
        raise Refusal(f'{rel}: {OPEN!r} appears without {CLOSE!r} — restore '
                      f'the closing marker (or delete the opening one); '
                      f'nothing was written')
    if end < start:
        raise Refusal(f'{rel}: {CLOSE!r} appears BEFORE {OPEN!r} — the markers '
                      f'are reversed; swap them back, nothing was written')
    return text[:start] + block + text[end + len(CLOSE):]


def targets(cfg: model.PmConfig) -> list[Path]:
    out = []
    for mdir in model.milestone_dirs(cfg):
        out.append(mdir / model.MILESTONE_DOC)
        out.extend(model.feature_files(mdir))
    return out


def has_block(text: str) -> bool:
    return OPEN in text and CLOSE in text


def sync(cfg: model.PmConfig, write: bool = True,
         existing_only: bool = False) -> list[tuple[Path, bool]]:
    """Returns (path, changed) per grain file. `write=False` only reports.

    `existing_only` restricts the walk to files that ALREADY carry a block —
    which is what V6 uses. A file with no execution list is not stale, it simply
    has none: the list is opt-in per file, so adopting it is `pm sync` once,
    not a gate that goes red on every tree that never asked for the feature.

    Raises `Refusal` — before ANY write — when a target is not UTF-8 or its
    marker pair is broken, naming every such file at once rather than the
    first. The tree is scanned whole either way, and a refused run leaves
    every file byte-identical.
    """
    plans: list[tuple[Path, str, str]] = []
    refusals: list[str] = []
    for path in targets(cfg):
        try:
            before = model.read_raw(path)
        except UnicodeDecodeError as err:
            refusals.append(f'{cfg.rel(path)}: not UTF-8 ({err}) — re-encode '
                            f'it; nothing was written')
            continue
        if existing_only and not has_block(before):
            continue
        try:
            plans.append((path, before, _replace(before, block_for(cfg, path),
                                                 cfg.rel(path))))
        except Refusal as err:
            refusals.append(str(err))
    if refusals:
        raise Refusal('\n'.join(refusals))
    results = []
    for path, before, after in plans:
        changed = after != before
        if changed and write:
            apply.raise_on_error(apply.write(path, after))
        results.append((path, changed))
    return results
