"""skills.py — the devkit-writes-its-own-files family of pm verbs.

`cmd_init`, `cmd_install_skills` and `cmd_templates` install devkit-owned
files INTO the consumer — `repo/install.py`'s concern, not status-verb
concern — so they live beside each other here and `cli.py` only routes.

The decide/apply/report skeleton deliberately stays a sibling COPY of
`install.main`'s rather than a shared driver: the two genuinely diverge on
ownership (install-skills clobbers its own generated file — the
GUIDANCE_HEADER check — without `--force`; install.main does not), on the
refusal channel (Refused vs stderr+exit) and on report wording, and a driver
parameterized over all three reads worse than the two copies. What IS shared
is everything that must never diverge: the three refusal helpers
(`install.collision_refusal`, `install.destination_defect`,
`install.read_destination`) and the diff printer, single-homed in
`repo/install.py`.
"""
from __future__ import annotations

from pathlib import Path

from godot_devkit.core import apply
from godot_devkit.repo import install
from godot_devkit.repo.pm import model, templates
from godot_devkit.repo.pm.cli import USAGE, Refused, Usage, _ok

GUIDANCE_HEADER = 'GENERATED by godot-devkit'

ROADMAP_SEED = """# Roadmap

The permanent index: one row per shipped milestone, in ship order. Active detail lives
in each milestone's own `milestone.md` — anything more than the table belongs deeper in
the tree.

| Version | Name | Delivered | What shipped |
|---|---|---|---|
"""


def cmd_init(cfg: model.PmConfig, args: list[str]) -> int:
    """Stand up a PM tree in a repo that has none, and say what is left to do."""
    if args:
        raise Usage(USAGE)
    plan = apply.Plan()
    index = cfg.roadmap / model.ROADMAP_DOC
    if not cfg.roadmap.is_dir():
        plan.make_dir(cfg.roadmap, label=f'{cfg.roadmap_dir}/')
    if not index.is_file():
        plan.overwrite(index, ROADMAP_SEED, newline=None, label=cfg.rel(index))
    apply.raise_on_error(plan.apply(decide=False))
    made = [step.label for step in plan.steps]
    for m in made:
        _ok(f'created {m}')
    if not made:
        _ok(f'{cfg.roadmap_dir}/ already exists — leaving it alone')
    cmd_install_skills(cfg, [])

    # Everything below is the consumer's to wire; printing it beats a README
    # they have to go find, and it is short enough to paste.
    print()
    print('Next, in your own repo:')
    print()
    print('  1. Wire the gate into your per-change gate set:')
    print()
    print('       pm-scan:')
    print('       \t@godot-devkit check pm')
    print()
    print('  2. Declare any schema differences in devkit.toml (all optional):')
    print()
    print('       [pm]')
    print('       review_dir = "docs/reviews"   # where review records live')
    print('       # story_ordinal_prefix = true # if story FILES are NN-slug.md')
    print('       # checks = [...]              # add D8/D9 for'
          ' branch-per-milestone')
    print()
    print('  3. Scaffold your first milestone, then check it:')
    print()
    print('       godot-devkit pm new milestone 0.1 "First Milestone"')
    print('       godot-devkit pm validate')
    print()
    print('  4. Keep your OWN vocabulary local — what a milestone means here, which')
    print('     surfaces exist, who reviews what. The two installed files carry only')
    print('     what the CLI enforces and explains.')
    return 0


def cmd_install_skills(cfg: model.PmConfig, args: list[str]) -> int:
    """Write the execution-loop guidance into the consuming repo.

    Installed as a RULE, not a skill file, deliberately: `.claude/rules/*.md`
    with a `paths:` header auto-load for any agent touching the matched files,
    while a skill has to be invoked. The execution loop has to reach every
    agent that edits the PM tree without being asked for.

    Only the loop the CLI itself enforces ships here. Branching, versioning,
    release ceremony, dispatch, review rosters — the project's own SDLC — stay
    in the project's own rules, because they differ per repo and always will.
    """
    force = False
    diff = False
    for a in args:
        if a == '--force':
            force = True
        elif a == '--diff':
            diff = True
        else:
            raise Usage(f'unknown flag {a!r}')

    from importlib import resources
    from godot_devkit import __version__

    # (source markdown, destination). Two delivery modes on purpose:
    #   rule  — auto-loads for any agent touching the tree; the per-edit loop
    #           has to arrive unasked or it does not arrive at all.
    #   skill — invoked deliberately; the operations manual is what you reach
    #           for when planning or restructuring, not on every edit.
    plan = [
        ('pm-execution.md', cfg.root / '.claude' / 'rules' / 'pm-execution.md'),
        ('pm-operations.md',
         cfg.root / '.claude' / 'skills' / 'pm-operations' / 'SKILL.md'),
    ]
    # Decided for BOTH entries before either is written. A refusal raised
    # mid-loop installs the first file, refuses the second, and still says
    # nothing was written — `nothing was written` has to be a claim about the
    # whole command, the same rule `pm init` follows for renames.
    # --diff reads and prints, off the SAME helper the install-* verbs use: a
    # second unified-diff printer would be a second answer to one question.
    if diff:
        for name, target in plan:
            body = (resources.files('godot_devkit.repo.pm.guidance')
                    .joinpath(name).read_text(encoding='utf-8'))
            install.print_diff(cfg.rel(target), target,
                               body.replace('{version}', f'v{__version__}'))
        return 0

    actions: list[tuple[str, Path, str]] = []
    collisions: list[str] = []
    defects: list[str] = []
    for name, target in plan:
        body = (resources.files('godot_devkit.repo.pm.guidance')
                .joinpath(name).read_text(encoding='utf-8'))
        body = body.replace('{version}', f'v{__version__}')
        # The same pre-decided discipline as the other two install verbs, from
        # the same helpers: a destination that is a directory, unwritable, or
        # undecodable is a refusal naming the path, never a traceback with one
        # file already on disk behind it.
        defect = install.destination_defect(target)
        if defect:
            defects.append(f'{cfg.rel(target)} {defect}')
            continue
        if target.is_file():
            existing, unreadable = install.read_destination(target)
            if unreadable:
                defects.append(f'{cfg.rel(target)} {unreadable}')
                continue
            if existing == body:
                actions.append(('current', target, body))
                continue
            # A file we did not generate — or one somebody edited — is theirs,
            # not ours. Clobbering it silently is how a project loses a local
            # decision it made on purpose.
            if (existing is None
                    or GUIDANCE_HEADER not in existing) and not force:
                collisions.append(cfg.rel(target))
                continue
        actions.append(('write', target, body))
    if collisions:
        head, tail = install.collision_refusal(collisions)
        raise Refused(f'{head}\n{tail}')
    if defects:
        raise Refused(f'{len(defects)} destination(s) cannot be written:\n'
                      + '\n'.join(f'    {d}' for d in defects)
                      + '\nNothing was written. Fix the path(s) and re-run — '
                        'the command is idempotent.')

    # ONE plan: the destinations were decided above, and `core.apply` reports
    # exactly which of them landed. A loop that decided as it wrote is what
    # made this verb's twin half-install twice before it was one plan.
    writes = apply.Plan()
    for kind, target, body in actions:
        if kind != 'current':
            writes.overwrite(target, body, newline=None, label=cfg.rel(target))
    result = writes.apply(decide=False)
    written = [step.label for step in result.landed]
    landed = set(written)
    for kind, target, body in actions:
        if kind == 'current':
            _ok(f'{cfg.rel(target)} already current')
        elif cfg.rel(target) in landed:
            _ok(f'installed {cfg.rel(target)}')
        else:
            break
    if result.failed is not None:
        raise Refused(
            f'{result.failed.label} could not be written '
            f'({result.error}) — '
            + ('nothing was written' if not written else
               'ALREADY WRITTEN before this was reached: '
               + ', '.join(written))
            + '. Fix the path and re-run — the command is idempotent.')
    wrote = len(written)
    if wrote:
        _ok(f'godot-devkit v{__version__} — these two carry only what the pm CLI '
            f'itself enforces and explains. Your project\'s SDLC (branching, '
            f'versioning, release, dispatch, review rosters) stays in your own '
            f'rules and agents.')
    return 0


def cmd_templates(cfg: model.PmConfig, args: list[str]) -> int:
    """Copy the packaged templates into the project so they can be edited."""
    force = '--force' in args
    for a in args:
        if a != '--force':
            raise Usage(f'unknown flag {a!r}')
    try:
        written, variants = templates.install(cfg, force)
    except templates.MissingTemplate as err:
        raise Usage(str(err)) from err
    for path in written:
        _ok(f'installed {cfg.rel(path)}')
    for other, slot in variants:
        _ok(f'{cfg.template_dir}/{other} is a case variant of {slot} and was '
            f'NOT written past — the loader reads EXACT names, so that file is '
            f'never used; `git mv --force {cfg.template_dir}/{other} '
            f'{cfg.template_dir}/{slot}`, then re-run')
    if not written:
        _ok(f'{cfg.template_dir}/ already populated (--force to overwrite)')
    return 0
