"""install.py — ship a file into a consuming repo, once, from one source.

`pm install-skills` established the idiom and these are its siblings. The
reason it is a VERB rather than three hand-written copies is the reason this
whole package exists: a contract pasted into three repos is three contracts a
week later, and the drift is invisible because each copy looks fine on its own.

Two things ship here, and both are shape rather than content:

  install-ci      a workflow that runs `godot-devkit task verify`. What that
                  executes is entirely the project's — see repo/tasks.py — so
                  the workflow itself carries almost nothing and is identical
                  everywhere. The ONE substituted value is where the toolkit
                  comes from, and it is filled with the installing build's own
                  version, so the pin is correct by construction.

  install-agents  the reviewer and builder contracts, as AGENT DEFINITIONS.
                  Deliberately not `.claude/rules/*`: it is measured that a
                  rules file never reaches a subagent's spawn context while its
                  definition does, so a contract written as a rule is a contract
                  that arrives nowhere.

The clobber guard is `pm install-skills`'s, for its reason: a file the tool did
not generate is the project's, and overwriting one silently is how a repo loses
a local decision it made on purpose.
"""
from __future__ import annotations

import sys
from importlib import resources
from pathlib import Path

from godot_devkit import __version__
from godot_devkit.core.project import repo_root

GENERATED_HEADER = 'GENERATED by godot-devkit'
PACKAGE = 'godot_devkit.repo.installables'

# (source name under installables/, destination relative to the repo root).
PLANS: dict[str, tuple[tuple[str, str], ...]] = {
    'install-ci': (
        ('ci-verify.yml', '.github/workflows/verify.yml'),
    ),
    'install-agents': (
        ('verification-reviewer.md', '.claude/agents/verification-reviewer.md'),
        ('verification-builder.md', '.claude/agents/verification-builder.md'),
    ),
}

USAGE = """usage: godot-devkit install-ci [--force]
       godot-devkit install-agents [--force]

install-ci      .github/workflows/verify.yml — runs `godot-devkit task verify`,
                which is whatever THIS repo declared for the `verify` role.
install-agents  the review and build contract, as AGENT DEFINITIONS under
                .claude/agents/ — the one place a subagent actually reads.

--force overwrites a destination this tool did not generate."""

# The one project-specific value in the workflow: where the toolkit is resolved
# from. Filled with the INSTALLING build's version, so a consumer's CI pins the
# devkit it was set up with rather than tracking a moving branch.
_SOURCE_PLACEHOLDER = '{devkit_source}'
_DEFAULT_SOURCE = 'git+https://github.com/cdowin/godot-devkit@v{version}'
# godot-devkit installing into godot-devkit must test the working tree, not a
# tag of itself — a self-hosted gate running the last release is a gate that has
# never seen the change in front of it.
_SELF_SOURCE = '.'
_SELF_NAME = 'godot-devkit'


def _source_for(root: Path) -> str:
    if (root / 'pyproject.toml').is_file():
        try:
            body = (root / 'pyproject.toml').read_text(encoding='utf-8')
        except (OSError, UnicodeDecodeError):
            body = ''
        if f'name = "{_SELF_NAME}"' in body:
            return _SELF_SOURCE
    return _DEFAULT_SOURCE.format(version=__version__)


def main(command: str, argv: list[str]) -> int:
    force = False
    for arg in argv:
        if arg == '--force':
            force = True
        elif arg in ('-h', '--help', 'help'):
            print(USAGE)
            return 0
        else:
            print(f'godot-devkit {command}: unknown flag {arg!r}',
                  file=sys.stderr)
            print(USAGE, file=sys.stderr)
            return 2

    root = repo_root()
    source = _source_for(root)
    wrote = 0
    for name, rel in PLANS[command]:
        body = (resources.files(PACKAGE).joinpath(name)
                .read_text(encoding='utf-8'))
        body = (body.replace('{version}', f'v{__version__}')
                    .replace(_SOURCE_PLACEHOLDER, source))
        target = root / rel
        if target.is_file():
            existing = target.read_text(encoding='utf-8')
            if existing == body:
                print(f'[install] {rel} already current')
                continue
            if GENERATED_HEADER not in existing and not force:
                print(f'godot-devkit {command}: {rel} exists and was not '
                      f'generated by this tool — move your version aside, or '
                      f'pass --force', file=sys.stderr)
                return 1
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(body, encoding='utf-8')
        print(f'[install] wrote {rel}')
        wrote += 1
    if wrote and command == 'install-ci':
        print(f'[install] the workflow runs `godot-devkit task verify` and '
              f'nothing else. What that executes is devkit.toml [tasks] '
              f'verify — run `godot-devkit check tasks` to confirm it resolves.')
    if wrote and command == 'install-agents':
        print(f'[install] godot-devkit v{__version__} — these carry the review '
              f'and build contract only: run adversarial input, ship a test '
              f'that failed against HEAD, verify through `task quick`. Your '
              f'project\'s own agents, rosters and dispatch model stay yours.')
    return 0
