"""install.py — ship a file into a consuming repo, once, from one source.

`pm install-skills` established the idiom and these are its siblings. The
reason it is a VERB rather than three hand-written copies is the reason this
whole package exists: a contract pasted into three repos is three contracts a
week later, and the drift is invisible because each copy looks fine on its own.

Two things ship here, and both are shape rather than content:

  install-ci      a workflow that runs `godot-devkit task verify`. What that
                  executes is entirely the project's — see repo/tasks.py — so
                  the workflow carries no gate of its own. The two things that
                  genuinely DIFFER per repo are declared in devkit.toml `[ci]`
                  and rendered here: the trigger, and the setup steps the gate
                  needs before it can run (a Godot toolchain, for both current
                  consumers). Shipping a skeleton that omitted them is how the
                  first generated workflow came out byte-identical everywhere
                  and unable to run anywhere.

  install-agents  the reviewer and builder contracts, as AGENT DEFINITIONS.
                  Deliberately not `.claude/rules/*`: it is measured that a
                  rules file never reaches a subagent's spawn context while its
                  definition does, so a contract written as a rule is a contract
                  that arrives nowhere.

The clobber guard is `pm install-skills`'s, for its reason: a file the tool did
not generate is the project's, and overwriting one silently is how a repo loses
a local decision it made on purpose. It is decided for EVERY entry in the plan
before the first byte is written — the same rule the PM scaffolder states as
"every refusal the grain can raise is decided before the first rename runs".
A refusal raised mid-loop leaves a half-installed repo behind and still says
nothing was written; `nothing was written` has to be a claim about the whole
command, not about the entry the refusal happened to land on.
"""
from __future__ import annotations

import json
import sys
from importlib import resources
from pathlib import Path

from godot_devkit import __version__
from godot_devkit.core import apply
from godot_devkit.core.config import ConfigError, config_section, str_tuple
from godot_devkit.core.project import repo_root

GENERATED_HEADER = 'GENERATED by godot-devkit'
PACKAGE = 'godot_devkit.repo.installables'

# (source name under installables/, destination relative to the repo root).
PLANS: dict[str, tuple[tuple[str, str], ...]] = {
    'install-ci': (
        ('ci-verify.yml', '.github/workflows/verify.yml'),
    ),
    'install-agents': (
        ('verification-reviewer.md', '.claude/agents/verification-reviewer.md'),
        ('verification-builder.md', '.claude/agents/verification-builder.md'),
    ),
}

USAGE = """usage: godot-devkit install-ci [--force]
       godot-devkit install-agents [--force]

install-ci      .github/workflows/verify.yml — runs `godot-devkit task verify`,
                which is whatever THIS repo declared for the `verify` role.
                Its trigger and its setup steps come from devkit.toml [ci].
install-agents  the review and build contract, as AGENT DEFINITIONS under
                .claude/agents/ — the one place a subagent actually reads.

--force overwrites a destination this tool did not generate."""

# The one project-specific value in the workflow: where the toolkit is resolved
# from. Filled with the INSTALLING build's version, so a consumer's CI pins the
# devkit it was set up with rather than tracking a moving branch.
_SOURCE_PLACEHOLDER = '{devkit_source}'
_DEFAULT_SOURCE = 'git+https://github.com/cdowin/godot-devkit@v{version}'
# godot-devkit installing into godot-devkit must test the working tree, not a
# tag of itself — a self-hosted gate running the last release is a gate that has
# never seen the change in front of it.
_SELF_SOURCE = '.'
_SELF_NAME = 'godot-devkit'


def _source_for(root: Path) -> str:
    if (root / 'pyproject.toml').is_file():
        try:
            body = (root / 'pyproject.toml').read_text(encoding='utf-8')
        except (OSError, UnicodeDecodeError):
            body = ''
        if f'name = "{_SELF_NAME}"' in body:
            return _SELF_SOURCE
    return _DEFAULT_SOURCE.format(version=__version__)


# --- devkit.toml [ci] --------------------------------------------------------
# Same principle as [tasks]: devkit owns the SHAPE (checkout, uv, one gate
# command), the project owns what only it can know. `verify` resolves to a
# target that needs a game engine in both consumers, and nothing in a generic
# skeleton can provision one — so the project declares it:
#
#     [ci]
#     on = ["push", "pull_request", "workflow_dispatch"]
#     branches = ["main"]              # applies to push + pull_request
#
#     [[ci.setup]]                     # run after checkout, before the gate
#     name = "Setup Godot"
#     uses = "chickensoft-games/setup-godot@v2"
#     with = { version = "4.6.2", include-templates = false }
#
#     [[ci.setup]]
#     name = "Warm the import cache"
#     run = "godot --path . --headless --editor --quit 2>&1 || true"
#
# Every value below is validated before a line of YAML is emitted, and a
# malformed declaration is a ConfigError (exit 2). A generator that guessed at
# a bad declaration would write a workflow GitHub rejects at parse time — a
# failure the operator sees days later, in a place that does not name the typo.
_ON_PLACEHOLDER = '{ci_on}'
_SETUP_PLACEHOLDER = '{ci_setup}'

# The events this skeleton can emit CORRECTLY. `schedule` and `release` need
# payloads of their own, so they are refused by name rather than emitted half
# right; the day a consumer needs one, it earns the code that renders it.
_EVENTS = ('push', 'pull_request', 'workflow_dispatch', 'merge_group')
_BRANCH_EVENTS = ('push', 'pull_request')
# The default trigger runs the full gate on the trunk and on pull requests —
# NOT on every push to every branch. `verify` is a repo's heaviest target
# (`make milestone`, a full integration sweep in one consumer); firing it on
# each work-in-progress push burns CI on a tree nobody is asking about yet.
_DEFAULT_EVENTS = ('push', 'pull_request', 'workflow_dispatch')
# `["**"]` is the way to say every branch — an EMPTY list would read as "none"
# and mean the opposite, which is the trap core.config refuses everywhere else.
_DEFAULT_BRANCHES = ('main',)

_STEP_KEYS = ('name', 'uses', 'run', 'with')
_STEP_INDENT = ' ' * 6


def _scalar(where: str, value: object) -> str:
    """One YAML scalar, quoted so any string survives.

    JSON is a subset of YAML 1.2, so `json.dumps` of a string IS a valid
    double-quoted YAML scalar — colons, quotes, `${{ }}` and newlines included.
    Hand-written quoting is how a generator emits a file that parses on the
    values it was tested with and breaks on the first one it was not.
    """
    if isinstance(value, bool):
        return 'true' if value else 'false'
    if isinstance(value, int):
        return str(value)
    if isinstance(value, str):
        return json.dumps(value)
    raise ConfigError(f'{where} must be a string, number or true/false, '
                      f'got {value!r}')


def _key(where: str, key: object) -> str:
    """One YAML mapping key, ALWAYS quoted — for `_scalar`'s reason.

    There was a fast path here that emitted any `[A-Za-z0-9_-]+` key bare, and
    it was wrong for a whole class of names GitHub actions really use. YAML 1.1
    — what most readers apply, PyYAML included — resolves a bare `on`, `off`,
    `yes`, `no`, `y`, `n`, `true`, `false` or `null` to a BOOLEAN or a null, a
    bare `123` or `0x1f` to an integer, and a bare `1_000` to 1000. An input
    named `on` and one named `yes` both became `True` and COLLIDED into one key.
    Every VALUE in this file is already quoted for exactly this reason; a key is
    a string too.
    """
    if not isinstance(key, str) or not key:
        raise ConfigError(f'{where} has a non-string key {key!r}')
    return json.dumps(key)


def _render_on(sect: dict) -> str:
    events = str_tuple(sect, 'ci', 'on', _DEFAULT_EVENTS)
    branches = str_tuple(sect, 'ci', 'branches', _DEFAULT_BRANCHES)
    lines: list[str] = []
    seen: set[str] = set()
    for event in events:
        if event not in _EVENTS:
            raise ConfigError(
                f'[ci] on: {event!r} is not an event this workflow can '
                f'express — one of {", ".join(_EVENTS)}')
        if event in seen:
            raise ConfigError(f'[ci] on lists {event!r} twice')
        seen.add(event)
        lines.append(f'  {event}:')
        if event in _BRANCH_EVENTS:
            listed = ', '.join(_scalar('[ci] branches', b) for b in branches)
            lines.append(f'    branches: [{listed}]')
    return '\n'.join(lines)


def _render_step(step: dict, ordinal: int) -> str:
    where = f'[[ci.setup]] step {ordinal}'
    unknown = sorted(k for k in step if k not in _STEP_KEYS)
    if unknown:
        raise ConfigError(f'{where} has unknown key(s) {", ".join(unknown)} — '
                          f'a step carries {", ".join(_STEP_KEYS)}')
    action = [k for k in ('uses', 'run') if k in step]
    if len(action) != 1:
        raise ConfigError(
            f'{where} must declare exactly one of uses/run, got '
            f'{", ".join(action) or "neither"}')
    emitted: list[tuple[str, object]] = []
    if 'name' in step:
        emitted.append(('name', step['name']))
    emitted.append((action[0], step[action[0]]))
    lines = []
    for index, (key, value) in enumerate(emitted):
        lead = f'{_STEP_INDENT}- ' if index == 0 else f'{_STEP_INDENT}  '
        lines.append(f'{lead}{key}: {_scalar(f"{where} {key}", value)}')
    if 'with' in step:
        inputs = step['with']
        if not isinstance(inputs, dict):
            raise ConfigError(f'{where} `with` must be a table of action '
                              f'inputs, got {inputs!r}')
        if not inputs:
            raise ConfigError(f'{where} declares an empty `with` — remove the '
                              f'key rather than passing no inputs')
        lines.append(f'{_STEP_INDENT}  with:')
        for key, value in inputs.items():
            name = _key(f'{where} `with`', key)
            lines.append(f'{_STEP_INDENT}    {name}: '
                         f'{_scalar(f"{where} with.{key}", value)}')
    return '\n'.join(lines) + '\n'


def _render_setup(sect: dict) -> str:
    steps = sect.get('setup', [])
    if not isinstance(steps, list) or not all(
            isinstance(s, dict) for s in steps):
        raise ConfigError(
            f'[ci] setup must be a list of tables — declare each step as its '
            f'own [[ci.setup]], got {steps!r}')
    return ''.join(_render_step(step, i) for i, step in enumerate(steps, 1))


def _render(name: str, source: str) -> str:
    """One installable, rendered. Every substitution happens here."""
    body = (resources.files(PACKAGE).joinpath(name)
            .read_text(encoding='utf-8'))
    body = (body.replace('{version}', f'v{__version__}')
                .replace(_SOURCE_PLACEHOLDER, source))
    if _ON_PLACEHOLDER in body or _SETUP_PLACEHOLDER in body:
        # Read only for the installable that HAS the placeholders: a bad [ci]
        # table is not `install-agents`'s problem to fail on.
        sect = config_section('ci')
        body = body.replace(_ON_PLACEHOLDER, _render_on(sect))
        body = body.replace(f'{_SETUP_PLACEHOLDER}\n', _render_setup(sect))
    return body


# --- the verb ----------------------------------------------------------------
# Every refusal below is decided BEFORE the first byte is written, and the two
# helpers here are shared with `pm install-skills` — the third install verb this
# package ships. They were two copies until one of them got the plural wrong
# ("… SKILL.md exist and were not generated") and the other did not; a sentence
# written twice is a sentence that is right once.
def collision_refusal(collisions: list[str]) -> tuple[str, str]:
    """(what collided, what that means) — plural-correct, for any install verb.

    Two sentences rather than one string because the callers frame them
    differently: this module prefixes each line with `godot-devkit <command>:`,
    while the pm CLI raises them as one `Refused`.
    """
    if len(collisions) == 1:
        head = (f'{collisions[0]} exists and was not generated by this tool — '
                f'move your version aside, or pass --force')
    else:
        listed = '\n'.join(f'    {rel}' for rel in collisions)
        head = (f'{len(collisions)} destinations exist and were not generated '
                f'by this tool — move your versions aside, or pass --force:\n'
                f'{listed}')
    return head, ('nothing was written; the whole install is refused, not just '
                  'the first colliding file.')


# The wording this verb's refusals have always used, mapped from the closed
# `Obstruction` vocabulary `core.apply` decides in. A dict, not a sentence
# built at the call site: the check lives in one place and the phrasing lives
# in one place, and neither has to know the other's business.
_DEFECT_TEXT = {
    apply.Obstruction.IS_A_DIRECTORY: 'is a directory',
    apply.Obstruction.NOT_A_REGULAR_FILE: 'is not a regular file',
    apply.Obstruction.NOT_WRITABLE: 'is not writable',
}
_PARENT_TEXT = {
    apply.Obstruction.PARENT_IS_A_FILE: 'is not a directory',
    apply.Obstruction.PARENT_NOT_WRITABLE: 'is not writable',
}


def destination_defect(target: Path) -> str:
    """'' when `target` can be written, else what stands in the way — decided
    WITHOUT writing a byte.

    The all-or-nothing property used to cover collisions only, so every other
    way a write can fail arrived as a traceback, and two of them arrived AFTER
    the first file had already been written: a destination that is a directory,
    a destination that is read-only, a parent path that is a file. A stack trace
    is not a refusal — it names no repair, and its "nothing was written" is a
    claim nobody made.

    This function used to BE those checks. It is now a caller: `core.apply`
    decides, in the same closed vocabulary every other writer in this package
    is decided in, and this maps the reason to the sentence three install verbs
    already print. A second copy of "can this be written" is a second chance to
    answer it differently.

    SYMLINKS ARE FOLLOWED here, said out loud rather than left to a default: an
    install destination is an ordinary repo file, and a project that symlinks
    `.claude/agents/` somewhere deliberate is exercising a choice this tool has
    no business overriding. The scaffolder declares the opposite, because a
    symlinked grain slot points OUT of the grain it was asked to fill.

    Not a substitute for handling the write's own OSError: a permission can
    change between this call and the write, and TOCTOU is exactly the case that
    must still not traceback. This is what turns the common cases into a
    sentence naming the path.
    """
    blocked = apply.Plan().overwrite(
        target, '', symlink=apply.Symlink.FOLLOW).decide()
    if not blocked:
        return ''
    first = blocked[0]
    if first.reason in _DEFECT_TEXT:
        return _DEFECT_TEXT[first.reason]
    return f'cannot be created: {first.path} {_PARENT_TEXT[first.reason]}'


def read_destination(target: Path) -> tuple[str | None, str]:
    """(the file's text, or None when it is not ours to compare; a defect).

    A destination this cannot DECODE is not a file this tool generated — the
    generated header is ASCII — so it is treated as a collision rather than as
    an error, and `--force` overwrites it the same way it overwrites any other
    foreign file. An unreadable one (permissions, a race) is a defect: a
    collision check that silently skipped it would clobber whatever is there.
    """
    try:
        return target.read_text(encoding='utf-8'), ''
    except UnicodeDecodeError:
        return None, ''
    except OSError as err:
        return None, f'cannot be read ({err.strerror or err})'


def _defect_refusal(command: str, defects: list[str], wrote: list[str]) -> str:
    listed = '\n'.join(f'    {d}' for d in defects)
    what = ('nothing was written' if not wrote else
            'ALREADY WRITTEN before this was reached: ' + ', '.join(wrote))
    return (f'godot-devkit {command}: {len(defects)} destination(s) cannot be '
            f'written:\n{listed}\n'
            f'godot-devkit {command}: {what}. Fix the path(s) and re-run — the '
            f'command is idempotent.')


def main(command: str, argv: list[str]) -> int:
    force = False
    for arg in argv:
        if arg == '--force':
            force = True
        elif arg in ('-h', '--help', 'help'):
            print(USAGE)
            return 0
        else:
            print(f'godot-devkit {command}: unknown flag {arg!r}',
                  file=sys.stderr)
            print(USAGE, file=sys.stderr)
            return 2

    root = repo_root()
    source = _source_for(root)

    # Decide the WHOLE plan first — render every body, resolve every
    # destination, collect every collision — and touch nothing until it holds.
    plan: list[tuple[str, Path, str, str]] = []   # (kind, target, rel, body)
    collisions: list[str] = []
    defects: list[str] = []
    try:
        for name, rel in PLANS[command]:
            body = _render(name, source)
            target = root / rel
            kind = 'write'
            defect = destination_defect(target)
            if defect:
                defects.append(f'{rel} {defect}')
                continue
            if target.is_file():
                existing, unreadable = read_destination(target)
                if unreadable:
                    defects.append(f'{rel} {unreadable}')
                    continue
                if existing == body:
                    kind = 'current'
                elif (existing is None
                      or GENERATED_HEADER not in existing) and not force:
                    collisions.append(rel)
                    continue
            plan.append((kind, target, rel, body))
    except ConfigError as err:
        # A devkit.toml mistake is exit 2, never 1 (findings) and never 0.
        print(f'godot-devkit {command}: {err}', file=sys.stderr)
        return 2

    # Collisions first: they are the refusal a human is most likely to hit, and
    # a run that has both should name the one --force answers.
    if collisions:
        head, tail = collision_refusal(collisions)
        print(f'godot-devkit {command}: {head}\n'
              f'godot-devkit {command}: {tail}', file=sys.stderr)
        return 1
    if defects:
        print(_defect_refusal(command, defects, []), file=sys.stderr)
        return 1

    # ONE plan, decided above and applied here. `install-agents` half-installed
    # twice because the loop that wrote also decided: the third file's problem
    # arrived with the first two already on disk. `core.apply` returns what
    # LANDED, so the refusal below names it instead of guessing.
    writes = apply.Plan()
    for kind, target, rel, body in plan:
        if kind != 'current':
            writes.overwrite(target, body, newline=None, label=rel)
    # Everything answerable was answered above, so a failure here means the
    # filesystem changed under the plan. It is still a refusal that names what
    # it did — never a traceback, and never a silent "nothing was written" over
    # a directory that already has one.
    result = writes.apply(decide=False)
    written = [step.label for step in result.landed]
    landed = set(written)
    # Reported in PLAN order, and STOPPING where the plan stopped: a line
    # printed past the failure would describe a file that was never reached.
    for kind, target, rel, body in plan:
        if kind == 'current':
            print(f'[install] {rel} already current')
        elif rel in landed:
            print(f'[install] wrote {rel}')
        else:
            break
    if result.failed is not None:
        print(_defect_refusal(command,
                              [f'{result.failed.label} could not be written '
                               f'({result.error})'], written),
              file=sys.stderr)
        return 1
    wrote = len(written)
    if wrote and command == 'install-ci':
        print(f'[install] the workflow runs `godot-devkit task verify` and '
              f'nothing else. What that executes is devkit.toml [tasks] '
              f'verify — run `godot-devkit check tasks` to confirm it resolves.')
    if wrote and command == 'install-agents':
        print(f'[install] godot-devkit v{__version__} — these carry the review '
              f'and build contract only: run adversarial input, ship a test '
              f'that failed against HEAD, verify through `task quick`. Your '
              f'project\'s own agents, rosters and dispatch model stay yours.')
    return 0
