"""classdb.py — the engine's built-in property table, snapshotted, not booted.

`check props` has to tell a script's `@export` apart from an engine built-in
(`position`, `layer`, `texture`, ...). Godot knows that from ClassDB; we know it
from a static snapshot of `--dump-extension-api`, regenerated by
`tools/gen_classdb.py` when the target engine minor moves. Reading it is pure
parse — nothing here boots Godot.

Two things a caller can ask:
    `properties_of("Sprite2D")`  -> every property on the class AND its ancestors
    `is_known("Sprite2D")`       -> is the whole ancestor chain in the snapshot?
`is_known` is the honesty valve: an unknown class means the gate must report the
node as UNVERIFIED rather than guess (a false PASS is survivable, a false FAIL
gets the gate switched off).
"""
from __future__ import annotations

import json
from functools import lru_cache
from pathlib import Path

DATA = Path(__file__).resolve().parent / 'data' / 'classdb.json'

# Scene-stored properties Godot synthesizes at runtime via `_get_property_list`
# rather than declaring in ClassDB. Slash-form keys (`theme_override_colors/x`,
# `metadata/y`, `popup/item_0/text`) are covered by the generic `/` rule in the
# gate; these are the flat-named survivors, calibrated against real repos.
SYNTHESIZED_PROPERTIES = frozenset((
    '__meta__',      # legacy editor metadata blob
    '_bundled',      # PackedScene payload
    '_data',         # AnimationLibrary / Animation payload
    'libraries',     # AnimationPlayer animation libraries
    'script',        # handled explicitly by every caller, listed for safety
))


@lru_cache(maxsize=1)
def _table() -> dict[str, dict]:
    payload = json.loads(DATA.read_text(encoding='utf-8'))
    return payload['classes']


@lru_cache(maxsize=1)
def godot_version() -> str:
    return json.loads(DATA.read_text(encoding='utf-8'))['godot_version']


@lru_cache(maxsize=512)
def properties_of(class_name: str) -> frozenset[str]:
    """Every ClassDB property of `class_name` and of every ancestor class."""
    names: set[str] = set()
    seen: set[str] = set()
    current: str | None = class_name
    table = _table()
    while current and current in table and current not in seen:
        seen.add(current)
        names.update(table[current]['props'])
        current = table[current]['inherits']
    return frozenset(names)


@lru_cache(maxsize=512)
def is_known(class_name: str) -> bool:
    """True when `class_name` AND its whole ancestor chain are in the snapshot."""
    table = _table()
    seen: set[str] = set()
    current: str | None = class_name
    while current:
        if current in seen or current not in table:
            return False
        seen.add(current)
        current = table[current]['inherits']
    return True
